export const initialState = {
  syllabiList: [
    {
      id: 0,
      rubricCode: 'MATH',
      courseNumber: '1000',
      courseName: 'How to Add Numbers',
      courseCredits: '4.0',
      courseDesc: 'Learn the basic mathematical function of addition.',
      prereqs: '',
      coreqs: '',
      deliveryMethod: 'Hybrid',
      deptContactInfo: '8675309',
      courseGoals: 'Students should be able to add.',
      learningOutcomes: 'Addition',
      courseTopics: 'Addition, integers',
      revisionDate: 'Fall 2019',
      isInactive: false
    },
    {
      id: 1,
      rubricCode: 'CSCI',
      courseNumber: '1100',
      courseName: 'Using InfoTech',
      courseCredits: '3.0',
      courseDesc: 'Basic computer skills in Word, Excel, PowerPoint, email',
      prereqs: '',
      coreqs: '',
      deliveryMethod: 'Hybrid',
      deptContactInfo: '+18675309',
      courseGoals: 'Students should know how to use a computer.',
      learningOutcomes: 'Proficiency in Office Suite and emailing',
      courseTopics: 'Word, Excel, Powerpoint, cybersecurity, email, hardware',
      revisionDate: 'Spring 2020',
      isInactive: false
    },
    {
      id: 2,
      rubricCode: 'CSCI',
      courseNumber: '1260',
      courseName: 'Intro to Comp Sci II',
      courseCredits: '4.0',
      courseDesc: 'Learn Object-Oriented concepts and how to use an IDE.',
      prereqs: 'CSCI 1250',
      coreqs: '',
      deliveryMethod: 'Traditional',
      deptContactInfo: '5556666',
      courseGoals:
        'Understanding of polymorphism and other object-oriented programming concepts.',
      learningOutcomes:
        'Know how to perform object-oriented programming in Java.',
      courseTopics: 'Java, data types, classes, polymorphism, functions',
      revisionDate: 'Fall 2009',
      isInactive: false
    },
    {
      id: 3,
      rubricCode: 'MATH',
      courseNumber: '9000',
      courseName: 'Set Theory',
      courseCredits: '5.0',
      courseDesc: 'Learn how sets work.',
      prereqs: 'MATH 8050, MATH 7760',
      coreqs: '',
      deliveryMethod: 'Traditional',
      deptContactInfo: '1234567',
      courseGoals: 'Learn about sets.',
      learningOutcomes: 'Proficiency in manipulating sets',
      courseTopics: 'Sets',
      revisionDate: 'Fall 2020',
      isInactive: false
    },
    {
      id: 4,
      rubricCode: 'HIST',
      courseNumber: '1100',
      courseName: 'US History Before 1870',
      courseCredits: '3.0',
      courseDesc:
        'Learn about history leading to the formation  of the United States until the year 1870.',
      prereqs: '',
      coreqs: '',
      deliveryMethod: 'Online',
      deptContactInfo: 'hist@etsu.edu',
      courseGoals: "Inform students of the nation's history.",
      learningOutcomes: 'Know important dates in US history before 1870.',
      courseTopics: 'United States history',
      revisionDate: 'Fall 2019',
      isInactive: false
    },
    {
      id: 5,
      rubricCode: 'HIST',
      courseNumber: '1200',
      courseName: 'US History After 1870',
      courseCredits: '3.0',
      courseDesc: 'Learn about US history after the Civil War.',
      prereqs: '',
      coreqs: '',
      deliveryMethod: 'Online',
      deptContactInfo: 'hist@etsu.edu',
      courseGoals: "Inform students of the nation's history.",
      learningOutcomes: 'Know important dates in US history after 1870.',
      courseTopics: 'United States history',
      revisionDate: 'Fall 2019',
      isInactive: false
    },
    {
      id: 6,
      rubricCode: 'ART',
      courseNumber: '1000',
      courseName: 'Primary Colors',
      courseCredits: '2.0',
      courseDesc: 'Learn the primary colors.',
      prereqs: '',
      coreqs: '',
      deliveryMethod: 'Traditional',
      deptContactInfo: 'art@etsu.edu, 9831246',
      courseGoals:
        'Teach students what makes a color primary, and which colors are primary.',
      learningOutcomes: 'Identify primary and non-primary colors.',
      courseTopics: 'Primary colors',
      revisionDate: 'Fall 1992',
      isInactive: true
    }
  ],
  syllabusFormData: {
    rubric_ode: '',
    course_number: '',
    course_name: '',
    course_credits: '',
    course_desc: '',
    prereqs: '',
    coreqs: '',
    delivery_method: '',
    dept_contact_info: '',
    course_goals: '',
    learning_outcomes: '',
    course_topics: '',
    revision_date: '',
    is_inactive: false
  }
};
