import React from 'react';

import ReactPDF, {
  Text,
  Document,
  Font,
  Page,
  StyleSheet,
  Image,
  View,
  PDFViewer
} from '@react-pdf/renderer';
import Header from './DocumentSections/Header';
import ContactInfo from './DocumentSections/ContactInfo';
import SyllabusDetails from './DocumentSections/SyllabusDetails';

const styles = StyleSheet.create({
  page: {
    padding: 30
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    '@media max-width: 400': {
      flexDirection: 'column'
    }
  },
  image: {
    marginBottom: 10
  },
  leftColumn: {
    flexDirection: 'column',
    width: 170,
    paddingTop: 30,
    paddingRight: 15,
    '@media max-width: 400': {
      width: '100%',
      paddingRight: 0
    },
    '@media orientation: landscape': {
      width: 200
    }
  },
  footer: {
    fontSize: 12,
    textAlign: 'center',
    marginTop: 25,
    paddingTop: 10,
    borderWidth: 3,
    borderColor: 'gray',
    borderStyle: 'dashed',
    '@media orientation: landscape': {
      marginTop: 10
    }
  }
});

const Syllabus = props => (
  <Page {...props} style={styles.page}>
    <Header syllabus={props.syllabus} />
    <View style={styles.container}>
      <View style={styles.leftColumn}>
        <Image src="../Syllabison.png" style={styles.image} />
        <ContactInfo syllabus={props.syllabus} />
      </View>
      <SyllabusDetails syllabus={props.syllabus} />
    </View>
    <Text
      style={styles.footer}
    >{`Generated by the Syllabison platform\nRevision Term: ${props.syllabus.revisionDate}`}</Text>
  </Page>
);

const SyllabusDocument = props => (
  <PDFViewer width="100%" height="100%">
    <Document title={`${props.syllabus.courseName} Syllabus`}>
      <Syllabus syllabus={props.syllabus} />
    </Document>
  </PDFViewer>
);

export default SyllabusDocument;
